stages:
  - build
  - deploy

buildFrontend:
  stage: build
  script:
  - npm ci
  artifacts:
    paths:
    - dist/
  only:
  - frontend
  tags:
  - mk4

deployFrontend:
  stage: deploy
  script:
  - rm -r /srv/http/static/*
  - cp -r dist/* /srv/http/static
  only:
  - frontend
  tags:
  - sonne

