stages:
  - build
  - deploy

buildFrontend:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - dist/
  only:
  - frontend
  tags:
  - buildfrontend

deployFrontend:
  stage: deploy
  script:
  - env
  only:
  - frontend
  tags:
  - sonne

