export = OrbitControls;
declare class OrbitControls {
  public object: any;
  public domElement: any;
  public enabled: any;
  public target: any;
  public minDistance: any;
  public maxDistance: any;
  public minZoom: any;
  public maxZoom: any;
  public minPolarAngle: any;
  public maxPolarAngle: any;
  public minAzimuthAngle: any;
  public maxAzimuthAngle: any;
  public enableDamping: any;
  public dampingFactor: any;
  public enableZoom: any;
  public zoomSpeed: any;
  public enableRotate: any;
  public rotateSpeed: any;
  public enablePan: any;
  public panSpeed: any;
  public screenSpacePanning: any;
  public keyPanSpeed: any;
  public autoRotate: any;
  public autoRotateSpeed: any;
  public enableKeys: any;
  public keys: any;
  public mouseButtons: any;
  public target0: any;
  public position0: any;
  public zoom0: any;
  public getPolarAngle: any;
  public getAzimuthalAngle: any;
  public saveState: any;
  public reset: any;
  public update: any;
  public dispose: any;
  constructor(object: any, domElement: any);
  public addEventListener(type: any, listener: any): void;
  public dispatchEvent(event: any): void;
  public hasEventListener(type: any, listener: any): any;
  public removeEventListener(type: any, listener: any): void;
}
